#!/bin/bash

if true ; then
	cat <<- EOF > /etc/logrotate.d/freepbx-ucp
	/var/log/asterisk/ucp_err.log
	/var/log/asterisk/ucp_out.log{
		size 50M
		missingok
		rotate 5
		notifempty
		sharedscripts
		create 0640 asterisk asterisk
		postrotate
		/usr/sbin/fwconsole pm2 --reload-logs -q
		endscript
	}
	EOF
fi

file="/etc/logrotate.d/freepbx-ucpnode"

if [ -f $file ] ; then
    rm -f $file
fi
